### ISSUE TITLE
[ENHANCEMENT] Module name

### ISSUE THREAD

**Issue by JBYT27** [BD103/BD103-Python#11]
This is just a suggestion, but this seems like a pretty good module for beginners to Python, or others who want to implement modules into other API's for themselves. So I was thinking, maybe change the module name from `BD103-Python` to maybe something that could be more globally known and "catchy"? Maybe like `ezpython` or something like that (Okay, that was stupid, but like, I'm trying xD).

I hope this helps!

> Really nice module btw :D

**Comment by BD103** [comment]
I really appreciate that you are taking interest in this package, but the original and only purpose of this library is to be a codebase that I can use in my other projects. Making this project beginner-friendly is an honorable goal, but I do not see changing the name improving it.

If you have any other suggestions, ideas, or re-implementations that I should add to this package, do tell me. Thanks for stopping by my little project. :)

_P.S. I won't rename BD103, but I might rename a subpackage if it's too confusing._

**Comment by JBYT27** [comment]
Oh, okay! No problem, it really does look cool and nice 👍
